name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build backend image
      run: docker build -t backend ./backend

    - name: Build service1 image
      run: docker build -t service1 ./service1

    - name: Build service2 image
      run: docker build -t service2 ./service2